Dev
krolik1591/chat_casino pull request #3
Opened 2023-08-13 19:34 UTC by krolik1591

2023-08-13 19:41 UTC, SvineruS requested changes

2023-08-13 19:41 UTC, SvineruS commented on bot/.env.example
> +REDIS=redis://redis:6379
нахуй

2023-08-13 19:41 UTC, SvineruS commented on bot/__main__.py
>          storage = MemoryStorage()
нахуй

2023-08-13 19:41 UTC, SvineruS commented on bot/handlers/games.py
> +async def on_user_join(message: types.Message, state: FSMContext):
спробувати зробити фільтр по новому чат мемберу

2023-08-13 19:41 UTC, SvineruS commented on bot/handlers/games.py
> +        await message.answer("Ви виграли, але всі промокоди вже використані!")
нахуй

2023-08-13 19:41 UTC, SvineruS commented on bot/handlers/games.py
> +    await message.answer(f"Ви отримали промокод {available_promo[0]}")
не писати промокод в чат

2023-08-13 19:41 UTC, SvineruS commented on docker-compose.yml
>          command: "redis-server /usr/local/etc/redis/redis.conf"
нахуй

2023-08-13 19:41 UTC, SvineruS commented on docs/docs.puml
> +@enduml
нахуй

2023-08-13 19:41 UTC, SvineruS commented on redis/config/redis.conf
> +dbfilename redis_dump.rdb
нахуй

2023-08-13 19:41 UTC, SvineruS commented on bot/requirements.txt
> +redis~=4.5.5
нахуй

2023-08-15 09:25 UTC, krolik1591 commented on bot/requirements.txt
> +redis~=4.5.5
шо йобнувся aiogram нахуй нєнє не обманеш

2023-08-15 09:30 UTC, krolik1591 commented on bot/handlers/games.py
> +        await message.answer("Ви виграли, але всі промокоди вже використані!")
а шо замість цього, якщо промокодів нема?

2023-08-15 21:27 UTC, merged